apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-cluster
  namespace: argocd-cluster
  labels:
    example: basic
spec:
  server:
    route:
      enabled: true
  dex:
    openShiftOAuth: true
    groups:
      - cluster-admins
      - argoread
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, cluster-admins, role:admin
      g, argoread, role:readonly
    scopes: '[groups]'